/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author chicu
 */
public class FrmPhongBan extends javax.swing.JPanel {

    JComboBox departmentCBB = new JComboBox();
    JTextField employeeIDField = new JTextField();
    JLabel searchLabel = new JLabel(new ImageIcon(getClass().getResource("/GUI/Images/buttonsearch.png")));
    JButton departmentAddButton = new JButton(new ImageIcon(getClass().getResource("/GUI/Images/add.png")));
    JButton departmentDeleteButton = new JButton(new ImageIcon(getClass().getResource("/GUI/Images/xoa.png")));
    JButton departmentSaveButton = new JButton(new ImageIcon(getClass().getResource("/GUI/Images/sua.png")));
    JButton departmentCancelButton = new JButton(new ImageIcon(getClass().getResource("/GUI/Images/huy.png")));
    /**
     * Creates new form FrmPhongBan
     */
    public FrmPhongBan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel2.getWidth(), jPanel2.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        departmentIDLabel = new javax.swing.JLabel();
        departmentIDField = new javax.swing.JTextField();
        departmentPhoneNumLabel = new javax.swing.JLabel();
        departmentNameField = new javax.swing.JTextField();
        departmentDeleteBtn = new javax.swing.JButton();
        departmentSaveBtn = new javax.swing.JButton();
        departmentCancelBtn = new javax.swing.JButton();
        departmentAddBtn = new javax.swing.JButton();
        departmentPhoneNumField = new javax.swing.JTextField();
        departmentNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        departmentTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel1.getWidth(), jPanel1.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel3.getWidth(), jPanel3.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        departmentBtn = new javax.swing.JLabel();
        searchBtn = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 600));

        departmentIDLabel.setText("Mã phòng ban:");

        departmentPhoneNumLabel.setText("Số điện thoại: ");

        departmentDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/xoa.png"))); // NOI18N
        departmentDeleteBtn.setText("Xóa");
        departmentDeleteBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        departmentSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/sua.png"))); // NOI18N
        departmentSaveBtn.setText("Sửa");
        departmentSaveBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        departmentCancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/huy.png"))); // NOI18N
        departmentCancelBtn.setText("Hủy");
        departmentCancelBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        departmentAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/add.png"))); // NOI18N
        departmentAddBtn.setText("Thêm");
        departmentAddBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        departmentNameLabel.setText("Tên phòng ban");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departmentNameLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentSaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(departmentIDLabel)
                    .addComponent(departmentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentPhoneNumLabel)
                    .addComponent(departmentPhoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(departmentIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(departmentNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(departmentPhoneNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentPhoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        departmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        departmentTable.setOpaque(false);
        departmentTable.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(departmentTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(207, 24));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Thông tin phòng ban");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 23));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));

        departmentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/house-20.png"))); // NOI18N
        departmentBtn.setText("Phòng ban");
        departmentBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 51, 255)));
        departmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        departmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentBtnMouseClicked(evt);
            }
        });

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/search.png"))); // NOI18N
        searchBtn.setText("Tìm kiếm");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(departmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void hiddenMenu(boolean flag, String noidung, String timtheo) {
        departmentIDLabel.setText(noidung);
        departmentNameLabel.setText(timtheo);
        departmentIDField.setVisible(flag);
        departmentCancelBtn.setVisible(flag);
        departmentAddBtn.setVisible(flag);
        departmentDeleteBtn.setVisible(flag);
        departmentSaveBtn.setVisible(flag);
        departmentNameField.setVisible(flag);
        departmentPhoneNumLabel.setVisible(flag);
        departmentPhoneNumField.setVisible(flag);
    }
    boolean init = true;
    
    public boolean getInit() {
        return this.init;
    }
    
    public void frmsearch(JPanel jPanel2,JTextField departmentIDField ,JLabel departmentIDLabel)
    {
        if(init)
        {
            departmentCBB.setSize(150,25);
            departmentCBB.setLocation(departmentIDField.getX(),departmentIDField.getY());
            departmentCBB.addItem("Mã Học Sinh");
            departmentCBB.addItem("Tên Học Sinh");
            jPanel2.add(departmentCBB);
            employeeIDField.setSize(150,25);
            employeeIDField.setLocation(departmentNameField.getX(),departmentNameField.getY());
            jPanel2.add(employeeIDField);
            searchLabel.setSize(170, 25);
            searchLabel.setLocation(departmentPhoneNumField.getX(), departmentPhoneNumField.getY());
            searchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jPanel2.add(searchLabel);
            searchLabel.addMouseListener(new MouseAdapter(){
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    //phuong thuc search 
                    
                }
            });
            departmentAddButton.setSize(90,30);
            departmentAddButton.setText("Thêm");
            departmentAddButton.setLocation(departmentAddBtn.getX(), departmentAddBtn.getY());
            departmentDeleteButton.setSize(90, 30);
            departmentDeleteButton.setText("Xóa");
            departmentDeleteButton.setLocation(departmentDeleteBtn.getX(), departmentDeleteBtn.getY());
            departmentSaveButton.setSize(90, 30);
            departmentSaveButton.setText("Sửa");
            departmentSaveButton.setLocation(departmentSaveBtn.getX(), departmentSaveBtn.getY());
            departmentCancelButton.setSize(90, 30);
            departmentCancelButton.setText("Hủy");
            departmentCancelButton.setLocation(departmentCancelBtn.getX(), departmentCancelBtn.getY());
            jPanel2.add(departmentAddButton);
            jPanel2.add(departmentCancelButton);
            jPanel2.add(departmentDeleteButton);
            jPanel2.add(departmentSaveButton);
            init=false;
        }
        else
        {
            departmentCBB.setVisible(true);
            employeeIDField.setVisible(true);
            searchLabel.setVisible(true);
            departmentAddButton.setVisible(true);
            departmentCancelButton.setVisible(true);
            departmentDeleteButton.setVisible(true);
            departmentSaveButton.setVisible(true);
        }
               
    }
    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        hiddenMenu(false, "Chọn phòng ban: ", "Nhập mã nhân viên: ");
        frmsearch(jPanel2, departmentIDField, departmentIDLabel);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void departmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentBtnMouseClicked
        // TODO add your handling code here:
        if (!getInit()) {
            hiddenMenu(true, "Mã phòng ban", "Tên phòng ban");
            departmentCBB.setVisible(false);
            employeeIDField.setVisible(false);
            searchLabel.setVisible(false);
            departmentAddButton.setVisible(false);
            departmentCancelButton.setVisible(false);
            departmentDeleteButton.setVisible(false);
            departmentSaveButton.setVisible(false);
        }
    }//GEN-LAST:event_departmentBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton departmentAddBtn;
    private javax.swing.JLabel departmentBtn;
    private javax.swing.JButton departmentCancelBtn;
    private javax.swing.JButton departmentDeleteBtn;
    private javax.swing.JTextField departmentIDField;
    private javax.swing.JLabel departmentIDLabel;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JLabel departmentNameLabel;
    private javax.swing.JTextField departmentPhoneNumField;
    private javax.swing.JLabel departmentPhoneNumLabel;
    private javax.swing.JButton departmentSaveBtn;
    private javax.swing.JTable departmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchBtn;
    // End of variables declaration//GEN-END:variables
}
